# Generated by Django 3.1.2 on 2020-10-28 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0002_auto_20201021_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='bio_notes',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Biography Note Field'),
        ),
        migrations.AddField(
            model_name='person',
            name='notes',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Note Field'),
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arabic_title', models.CharField(blank=True, max_length=300, verbose_name='Title')),
                ('chinese_title', models.CharField(blank=True, max_length=300, verbose_name='Title')),
                ('author_name', models.CharField(blank=True, max_length=100, verbose_name='Author')),
                ('translator_name', models.CharField(blank=True, max_length=100, verbose_name='Translator')),
                ('pub_date', models.CharField(blank=True, max_length=50, verbose_name='Date')),
                ('type_of', models.CharField(blank=True, choices=[('b', 'Book'), ('m', 'Manuscript')], default='m', max_length=1, null=True, verbose_name='Type of the work')),
                ('summary', models.CharField(blank=True, max_length=1000, verbose_name='Summary')),
                ('num_pages', models.IntegerField(blank=True, null=True, verbose_name='Number of Pages')),
                ('transcribed', models.BooleanField(default=True, verbose_name='Transcribed')),
                ('author_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author_id', to='listing.person')),
                ('translator_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translator_id', to='listing.person')),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_url', models.CharField(blank=True, max_length=200, verbose_name='Image URL')),
                ('transcribed', models.BooleanField(default=True, verbose_name='Transcribed')),
                ('work_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_id', to='listing.work')),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='related_works',
            field=models.ManyToManyField(to='listing.Work'),
        ),
    ]
