# Generated by Django 3.1.2 on 2020-10-28 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0003_auto_20201028_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='type_of',
            field=models.CharField(blank=True, choices=[('au', 'Author'), ('as', 'Assembler'), ('ed', 'Editor'), ('sc', 'Scrivener'), ('tr', 'Translator'), ('ot', 'Others')], default='au', max_length=2, verbose_name='Roles of the person'),
        ),
    ]
